#!/bin/bash

protected_branch='master'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ ${protected_branch} = ${current_branch} ]
then
    echo "|!| You're about to make changes to master ... nope, that is not allowed!"
    exit 1 # push will not be executed
else
    exit 0 # push will be executed
fi
