#!/bin/bash

git_tag=$(git describe --abbrev=0 --tags)
package_version=$(node -p "require('./package.json').version")

echo "git tag is at ${git_tag}"
echo "package version is at ${package_version}"

echo "|?| Do you want to increase the package version?"
echo "[1] patch"
echo "[2] minor"
echo "[3] major"
read -n 1 < /dev/tty
echo

if [[ $REPLY != [123] ]]
then
    exit 0
fi

IFS=. read major minor patch <<< ${package_version}

((patch++))

if [ $REPLY -gt "1" ]; then
    ((minor++))
    patch="0"
fi

if [ $REPLY -gt "2" ]; then
    ((major++))
    minor="0"
fi

new_version="${major}.${minor}.${patch}"

(npm --no-git-tag-version version ${new_version}) >/dev/null

branch_name=$(git symbolic-ref --short -q HEAD)

(git add "./package.json")
(git commit -m "${branch_name} bump version from ${package_version} to ${new_version}")

exit 0
